### ISSUE TITLE
Missing amazonPayToken

### ISSUE THREAD

**Issue by gmile-chris** [amzn/amazon-pay-api-sdk-php#10]
Hi.

I am trying to use an external aquirer for processing the payments as described in: [https://amazon-pay-acquirer-guide.s3-eu-west-1.amazonaws.com/v2/amazon-pay-checkout/verify-checkout-info.html](https://amazon-pay-acquirer-guide.s3-eu-west-1.amazonaws.com/v2/amazon-pay-checkout/verify-checkout-info.html)

I am not able to get the amazonpayToken. I already contacted the amazon support, but they just answered with a copy and paste of the documentation.

Is there a trick for getting the required amazonpayToken?

In the meantime I switched to normal processing. Everything works as expected, but our company would like to process the amazon pay payments with adyen as aquirer: [https://docs.adyen.com/payment-methods/amazon-pay](https://docs.adyen.com/payment-methods/amazon-pay)

Thanks Chris

**Comment by bjguillot** [comment]
Send me an email (guillotb@amazon.com) and I'll work to connect you with someone familiar with Adyen integrations.

**Comment by gmile-chris** [comment]
Here is the solution from the Amazon Pay Support:

> As far as I see from the issue link reported below, the issue is related to the amazonPayToken not being returned from the API.
> This is probably due to the public Key ID being used to call the Amazon Pay API, as the one created in a self-service manner in Seller Central, would not enable the integration with Adyen.
> As per our [documentation](https://amazon-pay-acquirer-guide.s3-eu-west-1.amazonaws.com/v2/amazon-pay-checkout/get-set-up-for-integration.html#4-get-your-publickeyid), you would need to provide us with the public key you intend to use for the integration, so that we can provide you with the correct Public Key ID.

Thanks for the fast support.

**Comment by ChrisRadny** [comment]
@lluishi93 Yes, this is correct. You need to contact your account manager. I ended up with the standard amazon pay integration. I thought it will be easier to use adyen. It's too complicated, and will add an extra layer of problems in the future.
