### ISSUE TITLE
What exactly does "your merchant account must be whitelisted to use the Delivery Trackers API" mean?

### ISSUE THREAD

**Issue by chadsaun** [amzn/amazon-pay-api-sdk-php#12]
I've never read anything in Amazon's documentation that mentions needing to be whitelisted.

Do you have any more info on this?

**Comment by lemked** [comment]
Thanks for reporting this @chadsaun . This is indeed obsolete and not required anymore. It's been the case when the feature was still in a private launch phase, but has been made public to everyone in the meantime, so whitelisting isn't required anymore.

README has been updated.
