### ISSUE TITLE
phpseclib 3.x support

### ISSUE THREAD

**Issue by jaybeckr** [amzn/amazon-pay-api-sdk-php#16]
Some platforms, e.g. Magento 2.4.4 (currently in beta) require phpseclib/phpseclib ~3.0 themselves which prevents any this SDK from being installed. E.g. as a dependency for Amazon Pay Magento 2 Module - https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/composer.json

**Comment by shangamesh** [comment]
We are working on implementing to provide support for phpseclib 3.x along with another request. We have a plan to release new version in Jan 2022

**Comment by shangamesh** [comment]
This change is addressed in latest version : https://github.com/amzn/amazon-pay-api-sdk-php/releases/tag/2.3.0
