### ISSUE TITLE
Amazon pay always prompts a signature error

### ISSUE THREAD

**Issue by iiDestiny** [amzn/amazon-pay-api-sdk-php#18]
I have checked the documentation many times and then followed the integration guide to coding

https://developer.amazon.com/zh/docs/amazon-pay-checkout/add-the-amazon-pay-button.html

## PHP 

```
Route::any('t', function () {
        $config = [
            'public_key_id' => 'SANDBOX-AFXFSBQVGCOQVCKVTF3BZDJA',
            'private_key'   => base_path() . '/../' . config('services.amazon_pay.private_key'),
            'region'        => 'us',
            'sandbox'       => true,
        ];

        $client  = new \Amazon\Pay\API\Client($config);
        $payload = [
            'storeId'            => 'amzn1.application-oa2-client.43f65b01ae1448c2b6f2713f20cb31b9',
            "scopes"             => ["billingAddress"],
            'webCheckoutDetails' => [
                'checkoutReviewReturnUrl' => 'http://localhost:3000',
                'checkoutResultReturnUrl' => 'http://localhost:3000',
                'checkoutCancelUrl'       => 'http://localhost:3000',
            ],
        ];

        $signature = $client->generateButtonSignature($payload);

        return response()->json([
            'signature' => $signature, 'payloadString' => $payload,
        ]);
    });
```

 The values in my sandbox

![image](https://user-images.githubusercontent.com/17637481/148908816-db6c6c63-f071-478b-80d8-8b48ece26fdb.png)

## Front-end section

```
import { useEffect } from 'react'
import { amazonCheckoutJs } from 'utils/helper'
import { httpProvider } from 'utils/http'

const AmazonPay = () => {
    useEffect(() => {
        ;(async () => {
            const a = await httpProvider({
                url: `/t`,
                method: 'get',
            })
            console.log(a)
            const amazon = await amazonCheckoutJs()
            console.log(JSON.stringify(a.payloadString))

            amazon.Pay.renderButton('#AmazonPayButton', {
                // set checkout environment
                merchantId: 'A1UV7YCAO4HL9I',
                publicKeyId: 'SANDBOX-AFXFSBQVGCOQVCKVTF3BZDJA',
                ledgerCurrency: 'USD',
                // customize the buyer experience
                checkoutLanguage: 'en_US',
                productType: 'PayAndShip',
                placement: 'Product',
                sandbox: true,
                buttonColor: 'Gold',
                // configure Create Checkout Session request
                createCheckoutSessionConfig: {
                    payloadJSON: JSON.stringify(a.payloadString),
                    signature: a.signature, // signature generated in step 3
                },
            })
        })()
    }, [])

    return (
        <div>
            <div id="AmazonPayButton"></div>
        </div>
    )
}

export default AmazonPay

```

Format in newwork

api response

```
{"signature":"D18MTJkq4R3vFqIGIiYvZp4YB6oh0nvoBadb\/yv60SKCdlz+rbBf\/Job6bYMizEwHiNTcnjYhMlZzb+7LmtUMrVpiOBP2NVjsBZpWMdZp6zAKkKu1fysUzk8yVW6WVPeQlP1IULPswlPjT9bgOfViGgtTC7qJk+pWjZ0kjFWLjGgVhKYeUmeu7wMUM6Y3mTuvLJAPZjqBi0hCo5sytfaNHJptDJ0F6wuvTjmA2Rso541rSxCzr4\/uNX32POORyodnEMTvvstL+uz2L3J5HrAqYFw\/h4ml0+GDfgV91wT86abTLzfnBAFKryqEvf+LwbDZHrBOJE8wzyjMP3DUpWkRA==","payloadString":{"storeId":"amzn1.application-oa2-client.43f65b01ae1448c2b6f2713f20cb31b9","scopes":["billingAddress"],"webCheckoutDetails":{"checkoutReviewReturnUrl":"http:\/\/localhost:3000","checkoutResultReturnUrl":"http:\/\/localhost:3000","checkoutCancelUrl":"http:\/\/localhost:3000"}}}
```

![image](https://user-images.githubusercontent.com/17637481/148909339-9bb6c400-21f6-455e-b1d7-793ccecc0244.png)

## error

Clicking the pay button always gets a signature error

![image](https://user-images.githubusercontent.com/17637481/148909392-863d5b04-918c-4192-be48-26c83d294600.png)

**Comment by iiDestiny** [comment]
@shangamesh @bjguillot  thanks

**Comment by shangamesh** [comment]
Hi 
If you are using latest version of SDK (i.e 2.3.0) then as a part of signature button integration, "algorithm" need to be provided as additional field in "createCheckoutSessionConfig" while rendering Amazon Pay button.

Example of "createCheckoutSessionConfig" :
```
createCheckoutSessionConfig: {           
  	payloadJSON: '{"webCheckoutDetails":{"checkoutReviewReturnUrl":"https://localhost/test/checkoutReview.html"},"storeId": "amzn1.application-oa2-client.xxxxx","scopes": ["name", "email", "phoneNumber", "billingAddress"]}',
  	signature: 'SIGNATURE', // Signature Obtained by calling "generateButtonSignature(payload)" method
  	algorithm: 'AMZN-PAY-RSASSA-PSS-V2' // This Parameter is mandatory
} 
```

**Comment by iiDestiny** [comment]
yea, just pulled the latest version today

Thank you for your reply, I'm going to try it

**Comment by iiDestiny** [comment]
Thanks, it work

**Comment by shangamesh** [comment]
Thanks for the update

**Comment by iiDestiny** [comment]
![image](https://user-images.githubusercontent.com/17637481/166896377-17d9ba4a-0935-42c9-8b63-2155687c5eb0.png)
![image](https://user-images.githubusercontent.com/17637481/166896395-36dbea10-bcdf-4d9f-8dd4-6aa16b7ee863.png)


HI, I'm not sure what's going on, the code didn't change anything and suddenly it says signature mismatch again
@shangamesh

**Comment by iiDestiny** [comment]
![image](https://user-images.githubusercontent.com/17637481/166896916-7e9ac9f7-5e55-438e-a0ff-20bcc06a087e.png)

**Comment by shangamesh** [comment]
Hello,
Please use the following button code if you are using latest version of SDK (i.e 2.3.2)

```
createCheckoutSessionConfig: {           
  	payloadJSON: '{"webCheckoutDetails":{"checkoutReviewReturnUrl":"https://localhost/test/checkoutReview.html"},"storeId": "amzn1.application-oa2-client.xxxxx","scopes": ["name", "email", "phoneNumber", "billingAddress"]}',
  	signature: 'SIGNATURE', // Signature Obtained by calling "generateButtonSignature(payload)" method
} 
```
The field `algorithm: 'AMZN-PAY-RSASSA-PSS-V2'` is not required. We reverted the change of having the algorithm in v 2.3.1.  

Please use latest version of SDK & remove algorithm from button code. It will work

**Comment by iiDestiny** [comment]
Thanks

**Comment by iiDestiny** [comment]
@shangamesh  Hi, sorry to bother you again. After upgrading to version 2.6.2 based on the previous SDK version 2.3.2, I followed the release instructions to include the algorithm in the client retrieval. However, I'm still experiencing a signature failure. I am quite puzzled. 

### backend

![image](https://github.com/amzn/amazon-pay-api-sdk-php/assets/17637481/1296b14d-7979-416f-a040-96b00ee3bce0)

![image](https://github.com/amzn/amazon-pay-api-sdk-php/assets/17637481/11ac5f98-0f83-4f41-b658-13cd43f78a6b)

![image](https://github.com/amzn/amazon-pay-api-sdk-php/assets/17637481/203a1e18-b173-4336-9b61-9483b554bfcb)

### frontend

![image](https://github.com/amzn/amazon-pay-api-sdk-php/assets/17637481/e5d875ad-5d50-4af9-ae9c-0d768b505899)

###  sandbox result

![image](https://github.com/amzn/amazon-pay-api-sdk-php/assets/17637481/89e4ae04-1dab-41cc-8714-f5f4eccfa5b7)

> After the issue with version 2.3.2 last time, there were no code changes made. Only the algorithm identifier mentioned in the version release notes was added.

**Comment by iiDestiny** [comment]
![image](https://github.com/amzn/amazon-pay-api-sdk-php/assets/17637481/d204e9b0-e003-4a50-a85e-88b849b50a57)

**Comment by shangamesh** [comment]
@iiDestiny 
I took version 2.6.2 & tested the button signature. I can conform it is working fine (i.e button is not throwing InvalidSignature error)

I noticed that in $payload passed to generateButtonSignature method doesn't contain `storeId` which is required field. Can you pass `storeId` in payload & verify it once ?

**Comment by iiDestiny** [comment]
Thank you, I suspect that caching was affecting the signature. Now it is working properly.
