### ISSUE TITLE
Deprecation error with php8.1

### ISSUE THREAD

**Issue by jaybeckr** [amzn/amazon-pay-api-sdk-php#20]
When using the SDK with php 8.1, attempting to call `Client->getCheckoutSession()` produces an error:

`Deprecated Functionality: hash(): Passing null to parameter #2 ($data) of type string is deprecated in /var/www/html/vendor/amzn/amazon-pay-api-sdk-php/Amazon/Pay/API/Client.php on line 195`

This appears to be due to passing `null` as the payload for `apiCall()`, which is eventually fed into php's `hash()` which needs a string. See `Amazon\Pay\API\Client::hexAndHash()`

**Comment by shangamesh** [comment]
Addressed this issue in latest release [2.3.2](https://github.com/amzn/amazon-pay-api-sdk-php/releases/tag/2.3.2)
