### ISSUE TITLE
Missing merchantMetadata information

### ISSUE THREAD

**Issue by eliassk** [amzn/amazon-pay-api-sdk-php#24]
Hi,
Based on what Amazon Pay docs saying, I should get back in response from getting checkout session information about the 'merchantMetadata', but the object which I'm getting from the SDK always gives me null there, even at I can see this in Amazon Pay portal.
Do you know what is the reason of that?

**Comment by shangamesh** [comment]
Hi 
Whenever new checkout Session is created, when you try to call GetCheckoutSession API you will get 'merchantMetadata' as null in API response. If you want to change the 'merchantMetadata', you can call updateCheckoutSession API with request containing filed 'merchantMetadata'. Post calling updateCheckoutSession API, you will receive response with updated 'merchantMetadata' values.

I have tested the same & can confirm that merchantMetadata is updated posted calling updateCheckoutSession API.

Reference code snippet : https://github.com/amzn/amazon-pay-api-sdk-php#amazon-checkout-v2---update-checkout-session
