### ISSUE TITLE
Weird behaviour with checkoutLanguage

### ISSUE THREAD

**Issue by toyi** [amzn/amazon-pay-api-sdk-php#27]
I don't know if it's the right place for this issue, I post here because I was implementing the Amazon Pay button with this SDK but it's more related to the button itself.

I've noticed a weird behaviour.

The merchant region is EU and was registered from France, althrough I don't know if it's relevant here. Everything that follows was done in the sandbox environment.

If I render the Amazon Pay button with:

```json
{
    "merchantId": "A19Q**********",
    "publicKeyId": "SANDBOX-***********************",
    "ledgerCurrency": "EUR",
    "checkoutLanguage": "en_GB",
    "productType": "PayAndShip",
    "placement": "Cart",
    "buttonColor": "Gold",
    "createCheckoutSessionConfig": {
        "payloadJSON": "{\"webCheckoutDetails\":{\"checkoutReviewReturnUrl\":\"https://www.**********.com/order/review\",\"checkoutResultReturnUrl\":\"https://www.**********.com/order/confirmation\",\"checkoutCancelUrl\":\"https://www.**********.com/order/annulation\"},\"scopes\":[\"name\",\"email\",\"phoneNumber\",\"billingAddress\"],\"storeId\":\"amzn1.application-oa2-client.***************************\"}",
        "signature": "s9dh3Jeic2K48UY0454n******************************HoDfBVdrY0BGQ=="
    }
}
```

It doesn't work and gives me an error message in German. The same happens with `de_DE`.

![image](https://user-images.githubusercontent.com/15825155/168056483-637193e1-1188-4553-adec-b3b74b49d57c.png)

However, it works fine just by changing the language to `fr_FR`, `it_IT` or `es_ES`.

Is it something normal / documented somewhere (like `en_GB` and `de_DE` are not available in sandbox, something like that)?

Thank you

**Comment by shangamesh** [comment]
Hello
This Issues is not related to SDK.

We suspect that is due to an active Amazon buyer session in "live" on the [amazon.de](http://amazon.de/) endpoint - which is used for EUR merchants when checkoutLanguage is "en_GB" and "de_DE". Please to try on another browser, and also ensure to login with sandbox credentials
