### ISSUE TITLE
php_uname is not supported by all the hosting providers

### ISSUE THREAD

**Issue by alexiglesias31** [amzn/amazon-pay-api-sdk-php#43]
The SDK will throw a fatal error if the hosting provider doesn't allow to call the function `php_uname`

`CRITICAL Uncaught Error: Call to undefined function Amazon\Pay\API\php_uname() in []/vendor/amzn/amazon-pay-api-sdk-php/Amazon/Pay/API/Client.php:324`

This is a common issue out there, the SDK should have a fallback method in case `php_uname` is not available, it has been reported on other SDKs out there (e.g Stripe: https://github.com/stripe/stripe-php/issues/828).

**Comment by nayankumars** [comment]
Thanks for the reporting @alexiglesias31, fixed the issue in version [2.6.5](https://github.com/amzn/amazon-pay-api-sdk-php/releases/tag/2.6.5)
