### ISSUE TITLE
IPN Handling?

### ISSUE THREAD

**Issue by EvanShaw** [amzn/amazon-pay-api-sdk-php#7]
Is there any plan to add IPN Handling to this package? I'd rather not try and implement it myself if there is already a plan in the works.

Thanks

**Comment by EvanShaw** [comment]
@bjguillot Thanks for the response.

> Unlike in the V1 IPNs, you don't necessarily need to validate the signature on these V2 IPNs. The reason is because the IPNs just notify you of a state change--they don't actually report what the state has changed to in the IPN itself.

That makes sense. I think it would be helpful to add a note like that in the docs since a cursory search of how to actually parse SNS messages from Amazon will bring up AWS documentation that describes validating the signature and other things not necessarily related to Amazon Pay. Also, using IPN's is a much better solution than polling and should probably be encouraged as the best way to handle state changes.

Before your comment I copied the code from the `IpnHandler.php` class you wrote for the V1 SDK and it pretty much worked out of the box and like you said it's not a lot of code... so adding it wouldn't be too hard. But perhaps just clarifying in the README with what you've already stated would be enough.

**Comment by EvanShaw** [comment]
And since we're on the topic of IPN handling, is there any plan to add `setMerchantNotificationConfiguration` and `getMerchantNotificationConfiguration`? For our purposes, being able set IPN endpoints from our implementation rather than requiring the user to manually set them from Seller Central is pretty essential.

**Comment by bjguillot** [comment]
From what I understand, you can still use those API calls from the other SDK (https://github.com/amzn/amazon-pay-sdk-php).  The endpoints for setMerchantNotificationConfiguration and getMerchantNotificationConfiguration are still served from the mws.amazonservices.com endpoint, not the pay-api.amazon.com endpoint that this SDK is designed to work with.  Eventually that API should be migrated over to the end endpoint, but I don't have an ETA on that.  The IPN delivery URL for Checkout v2 should honor the settings made with the MWS endpoint APIs.  If you see that isn't happening for you, let me know we can dive deeper into it.

**Comment by EvanShaw** [comment]
@bjguillot Thanks for the info. I'll mark this as closed and use the old SDK for IPN endpoint registration.
