### ISSUE TITLE
Button Signature not static

### ISSUE THREAD

**Issue by rhambo** [amzn/amazon-pay-api-sdk-php#8]
The signature generated by the generateButtonSignature method does not seem to be static for me. 
Using this code

```
<?php
    include "vendor/autoload.php";

    $amazonpay_config = array(
        'public_key_id' => 'AE7IYD6IQKEYXY7UO56MYSJI',
        'private_key'   => 'keys/privatekey.pem',
        'region'        => 'DE',
        'sandbox'       => true
    );

    $client = new Amazon\Pay\API\Client($amazonpay_config);
    $payload = '{"storeId":"amzn1.application-oa2-client.xxxxx","webCheckoutDetails":{"checkoutReviewReturnUrl":"https://localhost/test/CheckoutReview.php","checkoutResultReturnUrl":"https://localhost/test/CheckoutResult.php"}}';
    for($i = 0; $i < 3; $i++){
        $signature = $client->generateButtonSignature($payload);
        echo $signature . "<br>";
    }
    ?>
```

I get an output like this 

> lJ9oDH6H3MGXuJqjXayh0KJMdt4AyjCP7EbaRTYuJ7LHP2c+3s7Azo9rIebWUuUg3IT58V3QHQvIG19hjKtiBHHpmtlyipcw6XNW9S2KkpN9L1CGB1lvhyS+qprvHSeWf5V5dKKJoPfH1AHeAHIOIt0TyjtGSYzzh3+cbQQcbIRHTvEM9U2a9oYqCzsr0cnKdFJq10urbnx+dzNMfiwfZuAbce7khWF08BxPo+jJpwoenLQzOuRBYf1R8eC9NUuIhczIR0xxLA9e8SqyijwSA0/TB5tolj2QG5//mkV/8qwH+jPAV9xVLUiXzfslQBBcKuE0WSBxPQPJSWFae7axeQ==
aqjH9g0eXU8c/clF5mAxgw37/mOABxrFPrU+B3Lpn6p8HNoLMBdvHzJyDtf67gDFoFc6dGyEqvemtlOZcVfsY+4YqKJJC91mHop/cuZr7QwK7Bo11ezLhqqs1E77+1praPP4T1qdRToquK+UfpTaJskF6GhBMbt1sIFf0uXlDjF987Xf61r6wPxzf4iubqE80S8oT0XaoiB9LRgr6hxVsMXZ9NHBqoM9Z2rUoDjV0CunhPUDBU1+TNdVMCSJG8XbBhPk31L59qBqzQ3c0/A4Efc+/lZbOcMaoIAKDtTkRMAgZXdq8d4Vq7L8Q+ySF5FmCN6AoQFR+lmrTBRhIgEtsw==
MJmBjZVmWRJUqMFnQRPlPWkhP2GEN62dNXk5cqcK/ttwxCGGYlgkH6hPGazxo89WaVLdo3EcNxvMBhiyyaGnSW2cQ1P2RHL2XJjGB3z+l3oiwOffgWH86yuyK+AKF7Ex4b56B0LaXDVANJNrxA5bRg5fJAR/MBTJNb5hxn2+595AsVgOdcaulFeu5vGkGigKXgESm+h3V5mn3YXh+bj23R3Smo4ZAVrPln0qHjl5QGy3aLlo2vtgSlu/UU5GBypeN9CdX2DjzfrtKEGG4SrEqqnLVSxxwMmtimNr4mXiFJrrUu3ufbVJ0aouCty0DI8Q5CyjcpsC/n5fYUvPttu1rQ==

As the signature changes every time, it of course does not match the expected signature which is why I get a "wrong signature" error when I try to implement the button.
I tried it with my full credentials as well, but it did not work for me on PHP 7.4.1 or 7.4.7.
What am I doing wrong?
Thanks in advance.

**Comment by bjguillot** [comment]
The signature changing every time you run the generate function is expected, and is a result of the RSA PSS algorithm being used.  They will all be valid representatives for the signature.  Since we aren't encoding a timestamp in this like we do for the regular API calls, any of the results can be used in a static fashion on your site.

Can you show the section of HTML/JS code you use for the button that makes use of your signature?  Be sure you treat the payloadJSON as a string (with quotes around it) using the exact same whitespacing as you used when you signed it, otherwise extra spaces, tabs, new lines can all cause the signature to not be computed the same.

Try those things and let us know what you find.

**Comment by rhambo** [comment]
To display the button I used this (with the real merchant id)
```
    <body>
    <div id="AmazonPayButton"></div>
    <script src="https://static-eu.payments-amazon.com/checkout.js"></script>
    <script type="text/javascript" charset="utf-8">
        amazon.Pay.renderButton('#AmazonPayButton', {
            merchantId: 'merchant_id',
            ledgerCurrency: 'EUR',
            sandbox: true,               
            checkoutLanguage: 'en_GB',
            productType: 'PayAndShip',
            placement: 'Cart',
            buttonColor: 'Gold',
            createCheckoutSessionConfig: {                     
                payloadJSON: '<?php echo $payload; ?>',
                signature: '<?php echo $signature; ?>',
                publicKeyId: 'AE7IYD6IQKEYXY7UO56MYSJI' 
            }   
        });
    </script>
</body>
```
When I click the button after adding the quotes, I now get an "UnknownException" error instead of the "wrong signature" error.

**Comment by bjguillot** [comment]
Can you confirm you are passing in your real merchantId in that field (instead of 'merchant_id')?  I assume you redacted it before pasting in GitHub, but just want to be sure.  

Can you provide a screenshot showing the UnknownException error?

**Comment by rhambo** [comment]
Yes, I just checked again, it is the real merchantId, as without it, I get an "InvalidRequest" error.

Here is the screenshot of the UnknownException

![image](https://user-images.githubusercontent.com/19958076/85177388-487c0e80-b27c-11ea-8673-a633a0ce570c.png)

**Comment by bjguillot** [comment]
I'm not seeing anything obviously wrong.  I just tested my own integration against our EU endpoints and I didn't see a problem like this.  Can you send your Merchant ID to me via email at amazon-pay-sdk@amazon.com so that we can take a deeper look?

**Comment by rhambo** [comment]
Of course, I just sent the mail.

**Comment by knitzie2** [comment]
Hey there, I just ran into the same problem and found it kind of difficult to see the resolution in the last comments (even though it was in there). So for any other who has the same difficulties:

1. Build your payload object as a String
`$payloadString = '{"storeId":"' . $store_id . '","webCheckoutDetails":{"checkoutReviewReturnUrl":"' . $checkout_review_return_url . '","checkoutResultReturnUrl":"' . $checkout_result_return_url . '"}}';`
2. create a signature out of it
`$signature = $client->generateButtonSignature($payloadString);`
3. render button with checkout session
`<body>
            <div id="AmazonPayButton"></div>
            <script src="https://static-eu.payments-amazon.com/checkout.js"></script>
            <script type="text/javascript" charset="utf-8">
                amazon.Pay.renderButton("#AmazonPayButton", {
                    // set checkout environment
                    merchantId: "ABCDEFG123456",
                    ledgerCurrency: "EUR",
                    sandbox: true,               
                    // customize the buyer experience
                    checkoutLanguage: "de_DE",
                    productType: "PayAndShip",
                    placement: "Cart",
                    buttonColor: "Gold",
                    // configure Create Checkout Session request
                    createCheckoutSessionConfig: {                     
                        payloadJSON: \'' . $payloadString . '\', 
                        signature: "' . $signature . '", 
                        publicKeyId: "YOURPUBLICKEY1234" 
                    }   
                });
            </script>
        </body>`

Most importantly make sure your payload is transmitted correctly in the HTML part. Esp. the quotation marks are important.
